authentication:
  enabled: true
  remember-me:
    key: P+TvGNKSGB909e+MFm4hid583N+d+ndbnwew/dNMvyo=
    expiration: 604 800 # 7 days

server:
  port: 8484
frontend:
  url: &frontUrl http://localhost:3000
spring:
  profiles:
    active: local
  application:
    name: financial-control
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/financial
    username: postgres
    password: 1234
cors:
  allowed-origins: *frontUrl
logging:
  level:
    app.core: debug
    org.springframework.security.web.authentication.rememberme: debug
