authentication:
  enabled: true
  remember-me:
    key: b/tL7tdd6tY6KLGW5ReocJLuZT+ARzJAvP2EuhNm8ro=
    expiration: 604 800 # 7 days


server:
  port: 8484
spring:
  application:
    name: financial-control
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-quiet-paper-a2x9rzsf-pooler.eu-central-1.aws.neon.tech/financial
    username: neondb_owner
    password: npg_vJmqn82jtNDw
logging:
  level:
    app.core: debug
