authentication:
  enabled: true

server:
  port: 8484
  application:
    name: financial-control
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-silent-truth-a2btkacz-pooler.eu-central-1.aws.neon.tech/financial
    username: financial_owner
    password: npg_aA7YO5HLgyde
logging:
  level:
    app.core: debug
