name: CI pipeline

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: building spring application
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: financial
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps: 
      - name: checkout repo
        uses: actions/checkout@v4 #

      # NOTE !!! - liquibase update action has java_home itself so it is unnessesarry to setup java explicitly
      #- name: setup java and maven
      #  uses: actions/setup-java@v3 
      # with:
      #    java-version: '17'
      #    distribution: 'temurin'
          
      - name: build with maven
        run: mvn clean install

      - name: Show JAVA_HOME
        run: echo "JAVA_HOME=$JAVA_HOME"

      - name: liquibase migration update dry-run
        uses: liquibase-github-actions/update@v4.32.0
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        with:
          changelogFile: migration/src/main/resources/db/master.xml
          url: "jdbc:postgresql://postgres:5432/financial"
          password: "1234"
          showSummary: "verbose"
          showSummaryOutput: "all"
          username: "postgres"
